repos:
  - repo: local
    hooks:
    - id: flake8
      name: flake8 linter
      stages: [commit]
      language: system
      entry: pipenv run flake8
      types: [python]
    - id: bandit
      name: bandit security linter
      stages: [commit]
      language: system
      entry: pipenv run bandit -r --configfile .bandit.yaml .
      types: [python]